// =========== JOB PARAMETERS (define here or pass in Integrator variables): =======================
   START_YEAR = 2024     // First FINANCIAL year (e.g. 2025 = FY2025). AU FY2025 starts Jul 2024.
   END_YEAR   = 0         // Last financial year. 0 = use current year + END_YEAR_OFFSET
   END_YEAR_OFFSET = 4    // Applied when END_YEAR=0. e.g. 0=current year, 2=current+2, -1=current-1
   FY_OFFSET  = 7         // FY start month: 0 or 1 = Jan (CY), 7 = AU FY
   YEAR_PREFIX  = "FY"    // Prefix for FY elements. CY elements use no prefix.
   OLAP_CONNECTION = "Jedox"
   DIMENSION_NAME  = "Month"
   CLEAR_DIMENSION = "true"   // "true" = full rebuild, "false" = incremental
   YEAR_MODE    = 3   // 1=FY only, 2=CY only, 3=Both (shared month leaves)
   DATE_LEVEL   = 1   // 1=Month only  2=Month + YYYY-MM-DD leaves  3=Retail only (requires RETAIL_CALENDAR)
   OPENING_BALANCE = "true" // "true" = add one '<year>-OB' opening-balance leaf per year (FY2025-OB / 2025-OB) as a direct child of the full year + each YTD marker. Hierarchy per YEAR_MODE: FY for 1&3, CY for 2
   WEEK_NUMBERS = "false"  // "true" = ISO 8601 Week Number on dates (DATE_LEVEL=2 only)
   ROLLING_WINDOWS = "12" // Comma-separated window sizes e.g. "7,9"; "" to disable
   ROLLING_START   = "2024-07" // First anchor month (YYYY-MM)
   PUBLIC_HOLIDAYS = "true"  // "true" = fetch public holidays (DATE_LEVEL=2 only)
   PUBLIC_HOLIDAY_COUNTRY = "AU"  // ISO country code: AU, NZ, GB, US, CA
   PUBLIC_HOLIDAY_STATES  = ""    // Comma-separated state codes (blank = national only). AU e.g. "NSW,VIC"
   WORKING_DAYS = "false"  // "true" = working day attributes (DATE_LEVEL=2 only)
   RETAIL_CALENDAR = ""   // "445", "454", or "" to disable. Required for DATE_LEVEL=3.
   DIM_DESCRIPTION = "*** This time dimension is system generated by Minerva Partners. ***"
   PROCESS_NAME = "Date Generator"
// ================================================================================================
import com.jedox.palojlib.interfaces.*
import com.jedox.palojlib.main.Consolidation
// -----------------------------------------------------------------------------
// 1. CONFIGURATION
// -----------------------------------------------------------------------------
int    startYear=START_YEAR.toInteger()
int    endYear=END_YEAR.toInteger()==0?Calendar.getInstance().get(Calendar.YEAR)+END_YEAR_OFFSET.toInteger():END_YEAR.toInteger()
int    fyOffset=FY_OFFSET.toInteger(), fyStart=fyOffset<=1?1:fyOffset
int    yearMode=YEAR_MODE.toInteger(), dateLevel=DATE_LEVEL.toInteger()
String pfx=YEAR_PREFIX.trim(), olapConn=OLAP_CONNECTION.trim(), dimName=DIMENSION_NAME.trim()
boolean clearDim=CLEAR_DIMENSION.trim().equalsIgnoreCase("true")
boolean retailOnly=dateLevel==3, doDates=dateLevel==2
boolean doFY=yearMode!=2, doCY=yearMode!=1
boolean doOB=OPENING_BALANCE.trim().equalsIgnoreCase("true")&&!retailOnly
boolean obFY=doOB&&doFY, obCY=doOB&&!doFY&&doCY  // YEAR_MODE: OB in FY for modes 1&3, in CY for mode 2
boolean doWeeks=doDates&&WEEK_NUMBERS.trim().equalsIgnoreCase("true")
boolean doWorkDays=doDates&&WORKING_DAYS.trim().equalsIgnoreCase("true")
boolean doHolidays=doDates&&PUBLIC_HOLIDAYS.trim().equalsIgnoreCase("true")
String  retailPattern=RETAIL_CALENDAR.trim().replaceAll("[^0-9]","")
boolean doRetail=doFY&&(doDates||retailOnly)&&(retailPattern=="445"||retailPattern=="454")
String  phCountry=PUBLIC_HOLIDAY_COUNTRY.trim().toUpperCase()
List<String> phStates=PUBLIC_HOLIDAY_STATES.trim()?PUBLIC_HOLIDAY_STATES.trim().split(",").collect{it.trim().toUpperCase()}:[]
List<Integer> rollingWindows=[]
if(!retailOnly&&ROLLING_WINDOWS.trim())ROLLING_WINDOWS.trim().split(",").each{String t=it.trim();if(t&&t.toInteger()>0)rollingWindows<<t.toInteger()}
boolean doRolling=!rollingWindows.isEmpty()
int rollStartY=0,rollStartM=0
if(doRolling){rollStartY=ROLLING_START.trim().substring(0,4).toInteger();rollStartM=ROLLING_START.trim().substring(5,7).toInteger()}
String dimDesc=DIM_DESCRIPTION.trim()+"\nlast updated by "+PROCESS_NAME.trim()+" on "+new java.text.SimpleDateFormat("yyyy-MM-dd HH:mm z").format(new Date())
def MA=["Jan","Feb","Mar","Apr","May","Jun","Jul","Aug","Sep","Oct","Nov","Dec"]
def ML=["January","February","March","April","May","June","July","August","September","October","November","December"]
def DA=["Mon","Tue","Wed","Thu","Fri","Sat","Sun"]
def QL=["Q1","Q2","Q3","Q4"]
if(startYear>endYear)       throw new IllegalArgumentException("START_YEAR must be <= END_YEAR")
if(fyOffset<0||fyOffset>12) throw new IllegalArgumentException("FY_OFFSET must be 0-12")
if(yearMode<1||yearMode>3)  throw new IllegalArgumentException("YEAR_MODE must be 1,2 or 3")
if(dateLevel<1||dateLevel>3)throw new IllegalArgumentException("DATE_LEVEL must be 1, 2 or 3")
if(retailOnly&&!doRetail)   throw new IllegalArgumentException("DATE_LEVEL=3 requires RETAIL_CALENDAR '445' or '454'")
LOG.info("=== "+dimName+" | mode="+yearMode+" | dates="+dateLevel+" | rolling="+rollingWindows+" | retail="+retailPattern+" | ob="+doOB+" | clear="+clearDim)
// -----------------------------------------------------------------------------
// 2. IN-MEMORY MODEL
// -----------------------------------------------------------------------------
def mMon   ={int y,int m->String.format("%04d-%02d",y,m)}
def fmtC   ={Calendar c->String.format("%04d-%02d-%02d",c.get(Calendar.YEAR),c.get(Calendar.MONTH)+1,c.get(Calendar.DAY_OF_MONTH))}
def addMths={int y,int m,int n->int m2=m+n;[(y+(m2-1).intdiv(12)),((m2-1)%12+1)]}
def mRange ={int sy,int sm,int ey,int em->List r=[];int y=sy,m=sm
    while(y<ey||(y==ey&&m<=em)){r<<mMon(y,m);def nx=addMths(y,m,1);y=nx[0];m=nx[1]};r}
def fyOf   ={int y,int m->(fyStart==1)?y:((m>=fyStart)?y+1:y)}
def fyQIdx ={int m->((m-fyStart+12)%12).intdiv(3)}
def mm     ={String n->n.substring(5,7).toInteger()}
def yy     ={String n->n.substring(0,4).toInteger()}
def pad2   ={int n->String.format("%02d",n)}
def buildYearData={boolean isFY->
    def data=[:]
    if(isFY){
        int iy=(fyStart==1)?startYear:(startYear-1),im=fyStart,ey=endYear,em=(fyStart==1)?12:(fyStart-1)
        while(iy<ey||(iy==ey&&im<=em)){
            int f=fyOf(iy,im)
            if(f>=startYear&&f<=endYear){
                if(!data[f])data[f]=[months:[],quarters:[:]]
                data[f].months<<[iy,im]
                String qn=pfx+f+" "+QL[fyQIdx(im)]
                if(!data[f].quarters[qn])data[f].quarters[qn]=[]
                data[f].quarters[qn]<<[iy,im]
            }
            def nx=addMths(iy,im,1);iy=nx[0];im=nx[1]
        }
    }else{
        int cyFrom=(yearMode==3)?((fyStart==1)?startYear:(startYear-1)):startYear
        for(int y=cyFrom;y<=endYear;y++){
            data[y]=[months:[],quarters:[:]]
            for(int m=1;m<=12;m++){
                data[y].months<<[y,m]
                String qn=y+" "+QL[(m-1).intdiv(3)]
                if(!data[y].quarters[qn])data[y].quarters[qn]=[]
                data[y].quarters[qn]<<[y,m]
            }
        }
    }
    data}
def fyData=doFY?buildYearData(true):[:]
def cyData=(!retailOnly&&doCY)?buildYearData(false):[:]
def fyLabels=fyData.keySet().sort(), cyLabels=cyData.keySet().sort()
LOG.info("  FY:"+fyLabels+" CY:"+cyLabels)
LinkedHashSet ms=new LinkedHashSet()
if(!retailOnly){fyLabels.each{f->fyData[f].months.each{p->ms<<mMon(p[0],p[1])}}
    cyLabels.each{y->cyData[y].months.each{p->ms<<mMon(p[0],p[1])}}}
List allMonths=ms.toList()
// Rolling
def rollingData=[:]
List allRWY=[],allRTDY=[],allRTGY=[],allRAY=[],allRWN=[],allRTDN=[],allRTGN=[],allRAN=[]
String rTop="Rolling Mth"
if(doRolling&&!allMonths.contains(mMon(rollStartY,rollStartM))){LOG.warn("  ROLLING_START outside range - skipped.");doRolling=false}
if(doRolling){
    int dey=yy(allMonths[-1]),dem=mm(allMonths[-1])
    rollingWindows.each{R->
        def fe=addMths(rollStartY,rollStartM,R-1)
        int fwy=fe[0]<=dey&&!(fe[0]==dey&&fe[1]>dem)?fe[0]:dey
        int fwm=fe[0]<dey||(fe[0]==dey&&fe[1]<=dem)?fe[1]:dem
        List anch=mRange(rollStartY,rollStartM,dey,dem)
        List anchWin=anch.findAll{a->def we=addMths(yy(a),mm(a),R-1);we[0]<dey||(we[0]==dey&&we[1]<=dem)}
        List anchTD=anch.size()>=R?anch[0..R-1]:anch
        List anchTG=anch.findAll{a->yy(a)<fwy||(yy(a)==fwy&&mm(a)<fwm)}
        Map wm=[:];anchWin.each{a->def we=addMths(yy(a),mm(a),R-1);wm[a]=mRange(yy(a),mm(a),we[0],we[1])}
        rollingData[R]=[anchWin:anchWin,anchTD:anchTD,anchTG:anchTG,wm:wm,fwy:fwy,fwm:fwm]
        String rp="-R"+pad2(R)
        allRWY<<"Rolling "+R+" Mth";allRTDY<<"Rolling "+R+" Mth TD";allRTGY<<"Rolling "+R+" Mth TG";allRAY<<"Rolling "+R+" Mth Avg"
        anchWin.each{a->allRWN<<a+rp;allRAN<<a+rp+" Avg"}
        anchTD.each{a->allRTDN<<a+rp+" TD"};anchTG.each{a->allRTGN<<a+rp+" TG"}
        LOG.info("  Rolling R"+R+": win="+anchWin.size()+" TD="+anchTD.size()+" TG="+anchTG.size())
    }
}
// Calendar element lists
def gl={cond,c->cond?c:[]}
def buildLists={labels,data,String p->
    def Q=gl(labels,labels.collectMany{lbl->data[lbl].quarters.keySet().sort()})
    def Y=gl(labels,labels.collect{p+it})
    def H=[];labels.each{lbl->H<<p+lbl+" H1"<<p+lbl+" H2"}
    def YTDY=gl(labels,labels.collect{p+it+" YTD"})
    def YTGY=gl(labels,labels.collect{p+it+" YTG"})
    def YTD=gl(labels,labels.collectMany{lbl->data[lbl].months.collect{mp->p+lbl+"-"+pad2(mp[1])+" YTD"}})
    def YTG=gl(labels,labels.collectMany{lbl->data[lbl].months.collect{mp->p+lbl+"-"+pad2(mp[1])+" YTG"}})
    def Top=[];if(labels){String px=(p?"FY":"CY");Top=[("All "+px),("All "+px+" YTD"),("All "+px+" YTG")]}
    [Q,Y,H,YTDY,YTGY,YTD,YTG,Top]}
def _fyL=buildLists(fyLabels,fyData,doFY?pfx:"")
def fyQ=_fyL[0],fyY=_fyL[1],fyH=_fyL[2],fyYTDY=_fyL[3],fyYTGY=_fyL[4],fyYTD=_fyL[5],fyYTG=_fyL[6],fyTop=_fyL[7]
def _cyL=buildLists(cyLabels,cyData,"")
def cyQ=_cyL[0],cyY=_cyL[1],cyH=_cyL[2],cyYTDY=_cyL[3],cyYTGY=_cyL[4],cyYTD=_cyL[5],cyYTG=_cyL[6],cyTop=_cyL[7]
if(!doFY||retailOnly)[fyQ,fyY,fyH,fyYTDY,fyYTGY,fyYTD,fyYTG,fyTop].each{it.clear()}
if(!doCY||retailOnly)[cyQ,cyY,cyH,cyYTDY,cyYTGY,cyYTD,cyYTG,cyTop].each{it.clear()}
// Opening balance leaves: one '<year element>-OB' per year (FY2025-OB / 2025-OB), in a single hierarchy per YEAR_MODE
List obEls=[]
if(obFY)fyLabels.each{f->obEls<<(pfx+f+"-OB")}
else if(obCY)cyLabels.each{y->obEls<<(""+y+"-OB")}
// Date leaves
List allDates=[];Map dtm=[:]
if(doDates){allMonths.each{mn->int yr=yy(mn),mo=mm(mn)
    int md=new GregorianCalendar(yr,mo-1,1).getActualMaximum(Calendar.DAY_OF_MONTH)
    for(int d=1;d<=md;d++){String dn=String.format("%04d-%02d-%02d",yr,mo,d);allDates<<dn;dtm[dn]=mn}
};LOG.info("  Dates: "+allDates.size())}
// Retail calendar
// DATE_LEVEL=2: weeks are CONSOLIDATED (date children, coexists with calendar hierarchy)
// DATE_LEVEL=3: weeks are NUMERIC leaves + RYTD/RYTG at period level, no calendar structure
List allRP=[],allRQ=[],allRY=[],allRWk=[],allRPYTD=[],allRPYTG=[],allRYTDY=[],allRYTGY=[]
String retailTop="All Retail",retailYTDTop="All Retail YTD",retailYTGTop="All Retail YTG"
Map<String,String> dtRetail=[:],dtRetailWk=[:],rwkPeriod=[:]
Map<String,String> rwkStartDate=[:],rwkEndDate=[:],rwkCurrentWeek=[:]
if(doRetail){
    int[] rw445=[4,4,5,4,4,5,4,4,5,4,4,5] as int[]
    int[] rw454=[4,5,4,4,5,4,4,5,4,4,5,4] as int[]
    int[] rw=retailPattern=="445"?rw445:rw454
    def nearestMon={int yr2,int mo2,int dy2->
        Calendar c=new GregorianCalendar(yr2,mo2-1,dy2)
        int dfm=((int)c.get(Calendar.DAY_OF_WEEK))==Calendar.SUNDAY?6:(c.get(Calendar.DAY_OF_WEEK)-Calendar.MONDAY)
        c.add(Calendar.DAY_OF_MONTH,dfm>3?(7-dfm):(-dfm));c}
    def fyCalStart={int fy->[fyStart==1?fy:(fy-1),fyStart==1?1:fyStart]}
    Set<String> dateSet=new HashSet<>(allDates)
    String todayStr=fmtC(Calendar.getInstance())
    fyLabels.each{fy->
        def _cs=fyCalStart(fy);int cy=(int)_cs[0],cm=(int)_cs[1]
        Calendar rys=nearestMon(cy,cm,1)
        def _ns=fyCalStart((int)fy+1);int ny=(int)_ns[0],nm=(int)_ns[1]
        long wks=(nearestMon(ny,nm,1).getTimeInMillis()-rys.getTimeInMillis())/(7L*86400000L)
        boolean w53=(wks==53)
        int[] periods=rw.clone();if(w53)periods[11]+=1
        String fyN=pfx+fy,ryN=fyN+"-R";allRY<<ryN
        if(retailOnly){allRYTDY<<ryN+" YTD";allRYTGY<<ryN+" YTG"}
        LOG.info("  Retail "+fyN+": start="+fmtC(rys)+" | "+wks+" wks"+(w53?" (53-week year)":""))
        Calendar cur=(Calendar)rys.clone()
        4.times{qi->
            String rqN=fyN+"-RPQ"+(qi+1);allRQ<<rqN
            3.times{pi->
                int pIdx=qi*3+pi
                String rpN=fyN+"-RP"+pad2(pIdx+1);allRP<<rpN
                if(retailOnly){allRPYTD<<rpN+" YTD";if(pIdx<11)allRPYTG<<rpN+" YTG"}
                periods[pIdx].times{wi->
                    String rwkN=rpN+"-W"+pad2(wi+1);allRWk<<rwkN;rwkPeriod[rwkN]=rpN
                    String wkS=fmtC(cur);Calendar ec=(Calendar)cur.clone();ec.add(Calendar.DAY_OF_MONTH,6)
                    rwkStartDate[rwkN]=wkS;rwkEndDate[rwkN]=fmtC(ec)
                    rwkCurrentWeek[rwkN]=(wkS<=todayStr&&todayStr<=fmtC(ec))?"Y":""
                    7.times{String dn=fmtC(cur)
                        if(dateSet.contains(dn)&&!dtRetailWk.containsKey(dn)){dtRetailWk[dn]=rwkN;dtRetail[dn]=rpN}
                        cur.add(Calendar.DAY_OF_MONTH,1)}
                }
            }
        }
    }
    LOG.info("  Retail: "+allRY.size()+" yrs | "+allRQ.size()+" qtrs | "+allRP.size()+" periods | "+allRWk.size()+" weeks"+(retailOnly?" | "+allRPYTD.size()+" RYTD | "+allRPYTG.size()+" RYTG":"")+(doDates?" | "+dtRetailWk.size()+" dates":""))
}
// Flat element+type list
def C=IElement.ElementType.ELEMENT_CONSOLIDATED;def N=IElement.ElementType.ELEMENT_NUMERIC
List allNames=[],allTypes=[]
def reg={List ns,t->ns.each{allNames<<it;allTypes<<t}}
if(doDates)reg(allDates,N)
if(!retailOnly)reg(allMonths,doDates?C:N)
if(doOB)reg(obEls,N)
[fyQ,fyY,fyH,fyYTDY,fyYTGY,fyYTD,fyYTG,fyTop,cyQ,cyY,cyH,cyYTDY,cyYTGY,cyYTD,cyYTG,cyTop].each{reg(it,C)}
if(doRolling){reg([rTop],C);[allRWY,allRTDY,allRTGY,allRAY,allRWN,allRTDN,allRTGN,allRAN].each{reg(it,C)}}
if(doRetail){
    reg(allRWk,retailOnly?N:C);reg(allRP,C);reg(allRQ,C);reg(allRY,C);reg([retailTop],C)
    if(retailOnly){reg(allRPYTD,C);reg(allRPYTG,C);reg(allRYTDY,C);reg(allRYTGY,C);reg([retailYTDTop,retailYTGTop],C)}
}
// Consolidations
List consos=[]
def cp ={p,c->consos<<[p,c,1.0d]}
def cp0={p,c->consos<<[p,c,0.0d]}
def bh={labels,data,String topY,String topTD,String topTG,boolean addOB->
    labels.each{lbl->
        String yN=data[lbl].quarters?data[lbl].quarters.keySet()[0].split(" Q")[0]:""
        String obN=yN+"-OB"
        List sq=data[lbl].quarters.keySet().sort()
        if(addOB)cp(yN,obN)   // OB = direct child of the full year (not quarters/halves)
        data[lbl].quarters.each{qn,pairs->pairs.each{p->cp(qn,mMon(p[0],p[1]))}}
        data[lbl].months.eachWithIndex{p,i->
            String ytdN=yN+"-"+pad2(p[1])+" YTD"
            if(addOB)cp(ytdN,obN)   // OB = first child of each YTD marker (running closing position)
            data[lbl].months[0..i].each{mp->cp(ytdN,mMon(mp[0],mp[1]))}
            if(i+1<data[lbl].months.size()){String ytgN=yN+"-"+pad2(p[1])+" YTG";data[lbl].months[i+1..-1].each{mp->cp(ytgN,mMon(mp[0],mp[1]))}}
            cp0(yN+" YTD",ytdN);cp0(yN+" YTG",yN+"-"+pad2(p[1])+" YTG")
        }
        cp(yN,yN+" H1");cp(yN,yN+" H2")
        sq[0..1].each{qn->cp(yN+" H1",qn)};sq[2..3].each{qn->cp(yN+" H2",qn)}
        cp0(topY,yN);cp0(topTD,yN+" YTD");cp0(topTG,yN+" YTG")
    }}
if(!retailOnly&&doFY)bh(fyLabels,fyData,"All FY","All FY YTD","All FY YTG",obFY)
if(!retailOnly&&doCY)bh(cyLabels,cyData,"All CY","All CY YTD","All CY YTG",obCY)
if(doDates)allDates.each{dn->cp(dtm[dn],dn)}
if(doRetail){
    if(doDates)dtRetailWk.each{dn,rwkN->cp(rwkN,dn)}
    rwkPeriod.each{rwkN2,rpN2->cp(rpN2,rwkN2)}
    fyLabels.each{fy->
        String fyN2=pfx+fy,ryN2=fyN2+"-R"
        4.times{qi->String rqN2=fyN2+"-RPQ"+(qi+1);cp(ryN2,rqN2);3.times{pi->cp(rqN2,fyN2+"-RP"+pad2(qi*3+pi+1))}}
        cp(retailTop,ryN2)
        if(retailOnly){
            List fpL=allRP.findAll{it.startsWith(fyN2+"-RP")}
            String ryYTDN=ryN2+" YTD",ryYTGN=ryN2+" YTG"
            fpL.eachWithIndex{rpN3,i->
                String rytdN=rpN3+" YTD";fpL[0..i].each{p->cp(rytdN,p)};cp0(ryYTDN,rytdN)
                if(i<fpL.size()-1){String rytgN=rpN3+" YTG";fpL[i+1..-1].each{p->cp(rytgN,p)};cp0(ryYTGN,rytgN)}
            }
            cp(retailYTDTop,ryYTDN);cp(retailYTGTop,ryYTGN)
        }
    }
}
if(doRolling)rollingWindows.each{R->
    String rp="-R"+pad2(R)
    String wY="Rolling "+R+" Mth",tdY="Rolling "+R+" Mth TD",tgY="Rolling "+R+" Mth TG",aY="Rolling "+R+" Mth Avg"
    double avgW=1.0d/R
    int fwy=rollingData[R].fwy,fwm=rollingData[R].fwm
    rollingData[R].anchWin.each{a->rollingData[R].wm[a].each{m->cp(a+rp,m);consos<<[a+rp+" Avg",m,avgW]};cp0(wY,a+rp);cp0(aY,a+rp+" Avg")}
    rollingData[R].anchTD.each{a->mRange(rollStartY,rollStartM,yy(a),mm(a)).each{m->cp(a+rp+" TD",m)};cp0(tdY,a+rp+" TD")}
    rollingData[R].anchTG.each{a->def ns=addMths(yy(a),mm(a),1)
        if(ns[0]<fwy||(ns[0]==fwy&&ns[1]<=fwm))mRange(ns[0],ns[1],fwy,fwm).each{m->cp(a+rp+" TG",m)};cp0(tgY,a+rp+" TG")}
    cp0(rTop,wY);cp0(rTop,tdY);cp0(rTop,tgY);cp0(rTop,aY)
}
// Attribute maps
Map prevMap=[:],nextMap=[:],nameMap=[:]
Map monValMap=[:],finYrMap=[:],qtrValMap=[:],yrValMap=[:]
Map currPeriodMap=[:],fiscalPeriodMap=[:],priorYearMap=[:],monthShortMap=[:],monthLongMap=[:]
Map dimMap=[:],wimMap=[:],fimMap=[:],diyMap=[:],wiyMap=[:],fiyMap=[:]
Map dayValMap=[:],weekNumMap=[:],dayAbbMap=[:]
Map dayTypeMap=[:],bizDayNumMap=[:],bizDaysInMonthMap=[:]
def allSeries=[allMonths,fyQ,fyY,fyH,fyYTDY,fyYTGY,fyYTD,fyYTG,fyTop,cyQ,cyY,cyH,cyYTDY,cyYTGY,cyYTD,cyYTG,cyTop]
if(doDates)  allSeries<<allDates
if(doRolling)allSeries+=[[rTop],allRWY,allRTDY,allRTGY,allRAY,allRWN,allRTDN,allRTGN,allRAN]
if(doRetail) allSeries+=[allRWk,allRP,allRQ,allRY,[retailTop]]
if(doRetail&&retailOnly)allSeries+=[allRPYTD,allRPYTG,allRYTDY,allRYTGY,[retailYTDTop],[retailYTGTop]]
allSeries.each{s->if(s)s.eachWithIndex{n,i->prevMap[n]=i==0?"":s[i-1];nextMap[n]=i==s.size()-1?"":s[i+1]}}
if(doOB){
    // OB.Next -> first day (DATE_LEVEL=2) or first month of its year; OB.Previous blank.
    // The shared month/date chain is left continuous, so first-period.Previous is NOT overridden.
    if(obFY)fyLabels.each{f->def fp=fyData[f].months[0];prevMap[pfx+f+"-OB"]="";nextMap[pfx+f+"-OB"]=doDates?String.format("%04d-%02d-01",fp[0],fp[1]):mMon(fp[0],fp[1])}
    else if(obCY)cyLabels.each{y->def fp=cyData[y].months[0];prevMap[""+y+"-OB"]="";nextMap[""+y+"-OB"]=doDates?String.format("%04d-%02d-01",fp[0],fp[1]):mMon(fp[0],fp[1])}
}
int cpY=Calendar.getInstance().get(Calendar.YEAR),cpM=Calendar.getInstance().get(Calendar.MONTH)+1
String cpMon=mMon(cpY,cpM)
allMonths.each{n->int yr=yy(n),mo=mm(n)
    nameMap[n]=MA[mo-1]+" "+yr;monValMap[n]=((yr-1900)*12+mo).toString()
    currPeriodMap[n]=(n==cpMon)?"Y":"";priorYearMap[n]=mMon(yr-1,mo)
    monthShortMap[n]=MA[mo-1];monthLongMap[n]=ML[mo-1]
    int d=new GregorianCalendar(yr,mo-1,1).getActualMaximum(Calendar.DAY_OF_MONTH)
    dimMap[n]=d.toString();wimMap[n]=String.format("%.4f",d/7.0d);fimMap[n]=String.format("%.4f",d/14.0d)
}
if(doRetail){
    allRY.each{n->nameMap[n]=n.replaceAll(/-R$/," Retail")}
    allRQ.each{n->def p=n.split("-RPQ");nameMap[n]=p[0]+" Retail Quarter "+p[1]}
    allRP.each{n->def p=n.split("-RP");nameMap[n]=p[0]+" Retail Period "+p[1].toInteger()}
    allRWk.each{n->def p=n.split("-RP");def w=p[1].split("-W");nameMap[n]=p[0]+" Retail Period "+w[0].toInteger()+" Week "+w[1].toInteger()}
    if(retailOnly){
        allRPYTD.each{n->def p=n.split("-RP");nameMap[n]=p[0]+" Retail Period "+p[1].split(" YTD")[0].toInteger()+" YTD"}
        allRPYTG.each{n->def p=n.split("-RP");nameMap[n]=p[0]+" Retail Period "+p[1].split(" YTG")[0].toInteger()+" YTG"}
        allRYTDY.each{n->nameMap[n]=n.replaceAll(/-R YTD$/," Retail YTD")}
        allRYTGY.each{n->nameMap[n]=n.replaceAll(/-R YTG$/," Retail YTG")}
        nameMap[retailYTDTop]="All Retail YTD";nameMap[retailYTGTop]="All Retail YTG"
    }
}
if(doOB)obEls.each{n->nameMap[n]=n.replaceAll(/-OB$/," Opening Balance")}
allNames.each{n->if(!nameMap[n])nameMap[n]=n}
if(doRolling)rollingWindows.each{R->String rp="-R"+pad2(R)
    rollingData[R].anchWin.each{a->nameMap[a+rp]=a+" Rolling "+R+" Mth";nameMap[a+rp+" Avg"]=a+" Rolling "+R+" Mth Avg"}
    rollingData[R].anchTD.each{a->nameMap[a+rp+" TD"]=a+" Rolling "+R+" Mth TD"}
    rollingData[R].anchTG.each{a->nameMap[a+rp+" TG"]=a+" Rolling "+R+" TG"}
}
def buildYearAttrs={labels,data,String p->
    labels.each{lbl->
        String yName=p+lbl;yrValMap[yName]=lbl.toString()
        data[lbl].quarters.each{qn,pairs->int cy=pairs[0][0],cm=pairs[0][1],calQ=(cm-1).intdiv(3)+1
            qtrValMap[qn]=((cy-1900)*4+(calQ-1)).toString()}
        data[lbl].months.eachWithIndex{pp,i->String mn=mMon(pp[0],pp[1])
            if(p){finYrMap[mn]=yName;fiscalPeriodMap[mn]=(i+1).toString()}
            nameMap[yName+"-"+pad2(pp[1])+" YTD"]=(p?yName+" "+MA[pp[1]-1]:lbl+" "+MA[pp[1]-1])+" YTD"
            nameMap[yName+"-"+pad2(pp[1])+" YTG"]=(p?yName+" "+MA[pp[1]-1]:lbl+" "+MA[pp[1]-1])+" YTG"
        }
        int days=data[lbl].months.sum{pp->new GregorianCalendar(pp[0],pp[1]-1,1).getActualMaximum(Calendar.DAY_OF_MONTH)}
        diyMap[yName]=days.toString();wiyMap[yName]=String.format("%.4f",days/7.0d);fiyMap[yName]=String.format("%.4f",days/14.0d)
    }}
if(!retailOnly&&doFY)buildYearAttrs(fyLabels,fyData,pfx)
if(!retailOnly&&doCY)buildYearAttrs(cyLabels,cyData,"")
if(doDates){
    Calendar base=new GregorianCalendar(1900,0,1);long mpd=86400000L
    allDates.each{dn->int yr=yy(dn.substring(0,7)),mo=mm(dn.substring(0,7)),dy=dn.substring(8,10).toInteger()
        Calendar cal=new GregorianCalendar(yr,mo-1,dy)
        dayAbbMap[dn]=DA[(cal.get(Calendar.DAY_OF_WEEK)+5)%7]
        nameMap[dn]=String.format("%02d",dy)+" "+MA[mo-1]+" "+yr
        dayValMap[dn]=((int)((cal.getTimeInMillis()-base.getTimeInMillis())/mpd)+1).toString()
        if(doWeeks){cal.setMinimalDaysInFirstWeek(4);cal.setFirstDayOfWeek(Calendar.MONDAY)
            weekNumMap[dn]=cal.getWeekYear()+"-W"+pad2(cal.get(Calendar.WEEK_OF_YEAR))}
    }
}
// Public holidays + observances
Map<String,String> phNational=[:],phState=[:],phObservance=[:]
if(doHolidays){
    Set<Integer> phYears=new HashSet<>();allDates.each{phYears<<yy(it.substring(0,7))}
    LOG.info("  Fetching holidays for "+phCountry+" "+phYears.sort())
    boolean fetchOk=true
    phYears.sort().each{yr->if(!fetchOk)return
        try{
            HttpURLConnection conn=(HttpURLConnection)new URL("https://date.nager.at/api/v3/PublicHolidays/"+yr+"/"+phCountry).openConnection()
            conn.setRequestMethod("GET");conn.setConnectTimeout(10000);conn.setReadTimeout(10000)
            conn.setRequestProperty("Accept","application/json")
            if(conn.getResponseCode()==200){
                def hols=new groovy.json.JsonSlurper().parseText(conn.getInputStream().getText("UTF-8"))
                hols.each{h->if(h.global==true){phNational[h.date]=h.name}else if(h.counties){
                    List sc=h.counties.collect{it.contains("-")?it.split("-")[1]:it}
                    List ms2=phStates.isEmpty()?sc:sc.findAll{s->phStates.any{it.equalsIgnoreCase(s)}}
                    if(ms2){String ex=phState[h.date];phState[h.date]=ex?(ex+"|"+ms2.join("|")):ms2.join("|")}
                }}
                LOG.info("  "+yr+": "+hols.size()+" records")
            }else{LOG.warn("  HTTP "+conn.getResponseCode()+" - holidays skipped.");fetchOk=false}
        }catch(Exception ex){LOG.warn("  Holiday fetch error: "+ex.getMessage());fetchOk=false}
    }
    if(!fetchOk){phNational.clear();phState.clear()}
    else LOG.info("  Holidays: "+phNational.size()+" national, "+phState.size()+" state.")
    def fix={int yr,int mo,int dy->String.format("%04d-%02d-%02d",yr,mo,dy)}
    def nth={int yr,int mo,int dow,int n->Calendar c=new GregorianCalendar(yr,mo-1,1)
        int df=(dow-c.get(Calendar.DAY_OF_WEEK)+7)%7;c.add(Calendar.DAY_OF_MONTH,df+(n-1)*7)
        String.format("%04d-%02d-%02d",c.get(Calendar.YEAR),c.get(Calendar.MONTH)+1,c.get(Calendar.DAY_OF_MONTH))}
    def ep={int yr,int off->int a=yr%19,b=yr.intdiv(100),cc=yr%100,d=b.intdiv(4),e=b%4,f=(b+8).intdiv(25)
        int g=(b-f+1).intdiv(3),h=(19*a+b-d-g+15)%30,i=cc.intdiv(4),k=cc%4
        int l=(32+2*e+2*i-h-k)%7,m=(a+11*h+22*l).intdiv(451),mo=(h+l-7*m+114).intdiv(31),dy=(h+l-7*m+114)%31+1
        Calendar ec=new GregorianCalendar(yr,mo-1,dy);ec.add(Calendar.DAY_OF_MONTH,off)
        String.format("%04d-%02d-%02d",ec.get(Calendar.YEAR),ec.get(Calendar.MONTH)+1,ec.get(Calendar.DAY_OF_MONTH))}
    def mDay={int yr,int mo->nth(yr,mo,Calendar.SUNDAY,2)};def fDay={int yr,int mo->nth(yr,mo,Calendar.SUNDAY,3)}
    phYears.each{yr->
        phObservance[fix(yr,2,14)]="Valentine's Day";phObservance[fix(yr,10,31)]="Halloween"
        phObservance[fix(yr,12,24)]="Christmas Eve";phObservance[fix(yr,12,31)]="New Year's Eve"
        switch(phCountry){
            case "AU": phObservance[fix(yr,4,24)]="ANZAC Day Eve";phObservance[mDay(yr,5)]="Mother's Day"
                phObservance[nth(yr,9,Calendar.SUNDAY,1)]="Father's Day"
                phObservance[nth(yr,11,Calendar.TUESDAY,1)]="Melbourne Cup";phObservance[ep(yr,-1)]="Easter Saturday";break
            case "NZ": phObservance[fix(yr,4,24)]="ANZAC Day Eve";phObservance[mDay(yr,5)]="Mother's Day"
                phObservance[nth(yr,9,Calendar.SUNDAY,1)]="Father's Day";phObservance[ep(yr,-1)]="Easter Saturday";break
            case "GB": phObservance[ep(yr,-21)]="Mothering Sunday";phObservance[fDay(yr,6)]="Father's Day"
                phObservance[fix(yr,11,5)]="Bonfire Night";break
            case "US": phObservance[mDay(yr,5)]="Mother's Day";phObservance[fDay(yr,6)]="Father's Day"
                phObservance[nth(yr,11,Calendar.THURSDAY,4)]="Thanksgiving";break
            case "CA": phObservance[mDay(yr,5)]="Mother's Day";phObservance[fDay(yr,6)]="Father's Day"
                phObservance[nth(yr,10,Calendar.MONDAY,2)]="Thanksgiving";break
            default:LOG.info("  No observances for "+phCountry)
        }
    }
    phNational.keySet().each{phObservance.remove(it)};phState.keySet().each{phObservance.remove(it)}
    LOG.info("  Observances: "+phObservance.size())
}
// Working day intelligence
if(doWorkDays){
    allMonths.each{mn->int bizSeq=0
        allDates.findAll{it.startsWith(mn)}.each{dn->
            Calendar cal=new GregorianCalendar(dn.substring(0,4).toInteger(),dn.substring(5,7).toInteger()-1,dn.substring(8,10).toInteger())
            int dow=cal.get(Calendar.DAY_OF_WEEK)
            boolean isWeekend=(dow==Calendar.SATURDAY||dow==Calendar.SUNDAY)
            boolean isPH=doHolidays&&(phNational.containsKey(dn)||(phStates&&phState.containsKey(dn)))
            dayTypeMap[dn]=isPH?"Public Holiday":isWeekend?"Weekend":"Weekday"
            if(!isWeekend&&!isPH){bizSeq++;bizDayNumMap[dn]=bizSeq.toString()}
        }
        bizDaysInMonthMap[mn]=bizSeq.toString()
    }
    LOG.info("  Working days: computed for "+allMonths.size()+" months.")
}
LOG.info("  Model: "+allNames.size()+" elements, "+consos.size()+" pairs")
// -----------------------------------------------------------------------------
// 3. CONNECT + FIND/CREATE DIMENSION
// -----------------------------------------------------------------------------
IDatabase  db =OLAP.getDatabase(olapConn)
IDimension dim=db.getDimensionByName(dimName)
if(dim==null){LOG.info("  Creating...");dim=db.addDimension(dimName);clearDim=true}
else LOG.info("  Found.")
// -----------------------------------------------------------------------------
// 4. DIFF AGAINST EXISTING ELEMENTS
// -----------------------------------------------------------------------------
Set<String> existing=new HashSet<>()
dim.getElements(false)?.each{existing<<it.getName()}
LOG.info("  Existing: "+existing.size())
if(clearDim&&existing){
    IElement[] consEls=dim.getElements(false).findAll{it.getType()==C} as IElement[]
    if(consEls?.length){dim.removeConsolidations(consEls);LOG.info("  Cleared consolidations on "+consEls.length+" parents.")}
    List<IElement> retyped=[]
    allNames.eachWithIndex{n,i->IElement el=dim.getElementByName(n,false);if(el&&el.getType()!=allTypes[i]){el.setType(allTypes[i]);retyped<<el}}
    if(retyped){dim.appendElements(retyped.toArray(new IElement[0]));LOG.info("  Retyped "+retyped.size())}
}
Set<String> newSet=(allNames as Set).findAll{!existing.contains(it)} as Set<String>
LOG.info("  New: "+newSet.size()+" | Skip: "+(allNames.size()-newSet.size()))
// -----------------------------------------------------------------------------
// 5. ADD ELEMENTS + CACHE
// -----------------------------------------------------------------------------
if(newSet){
    List addN=[],addT=[]
    allNames.eachWithIndex{n,i->if(newSet.contains(n)){addN<<n;addT<<allTypes[i]}}
    dim.addElements(addN.toArray(new String[0]),addT.toArray(new IElement.ElementType[0]))
    LOG.info("  Added "+addN.size())
}
Map<String,IElement> cache=[:]
dim.getElements(false).each{cache[it.getName()]=it}
LOG.info("  Cache: "+cache.size())
// -----------------------------------------------------------------------------
// 6. CONSOLIDATIONS
// -----------------------------------------------------------------------------
List arList=fyTop+cyTop+fyYTDY+fyYTGY+cyYTDY+cyYTGY
if(doOB)arList+=fyY+cyY+fyYTD+cyYTD  // OB parents (full year + monthly YTD markers) re-evaluate for the new OB child
if(doRolling)arList+=[rTop]+allRWY+allRTDY+allRTGY+allRWN+allRTDN+allRTGN+allRAN
if(doRetail) arList+=[retailTop]+allRY
if(doRetail&&retailOnly)arList+=[retailYTDTop,retailYTGTop]+allRYTDY+allRYTGY
Set<String> alwaysR=arList as Set<String>
List<IConsolidation> nc=[]
if(clearDim){
    consos.each{t->IElement pe=cache[t[0]],ce=cache[t[1]];if(pe&&ce)nc<<new Consolidation(pe,ce,(double)t[2])}
}else{
    consos.each{t->String p=t[0],c=t[1];double w=t[2]
        if(newSet.contains(p)||(alwaysR.contains(p)&&newSet.contains(c))){
            IElement pe=cache[p],ce=cache[c]
            if(pe&&ce)nc<<new Consolidation(pe,ce,w)
            else{if(!pe)LOG.warn("  Bad parent: "+p);if(!ce)LOG.warn("  Bad child: "+c)}
        }
    }
}
if(nc){
    LOG.info("  Consolidations: "+nc.size()+" ("+(clearDim?"update":"add")+"Consolidations)...")
    IConsolidation[] ncArr=nc.toArray(new IConsolidation[0])
    if(clearDim)dim.updateConsolidations(ncArr) else dim.addConsolidations(ncArr)
    LOG.info("  Done.")
}else LOG.info("  No consolidations.")
// -----------------------------------------------------------------------------
// 7. ATTRIBUTES
// -----------------------------------------------------------------------------
Set<String> ws=clearDim?new HashSet<>(allNames):new HashSet<>(newSet)
if(!clearDim){allSeries.each{s->if(!s)return;s.eachWithIndex{n,i->
    if(newSet.contains(n)){
        if(i>0&&!newSet.contains(s[i-1]))ws<<s[i-1]
        if(i<s.size()-1&&!newSet.contains(s[i+1]))ws<<s[i+1]
    }
}}}
LOG.info("  Attr writes: "+ws.size())
List attrNms=["Previous","Next","Name","Financial Year","Month Value","Quarter Value","Year Value",
              "Current Period","Fiscal Period","Prior Year","Month Short","Month Long",
              "Days In Month","Weeks In Month","Fortnights In Month",
              "Days In Year","Weeks In Year","Fortnights In Year"]
if(doDates)   {attrNms<<"Day Value";if(doWeeks)attrNms<<"Week";attrNms<<"Day"}
if(doHolidays) attrNms+=["Public Holiday","Public Holiday State","Observance"]
if(doWorkDays) attrNms+=["Day Type","Business Day Number","Business Days In Month"]
if(doRetail)   attrNms+=["Retail Period","Retail Week"]
if(retailOnly) attrNms+=["Week Start Date","Week End Date","Current Week"]
dim.addAttributes(attrNms.toArray(new String[0]),([IElement.ElementType.ELEMENT_STRING]*attrNms.size()).toArray(new IElement.ElementType[0]))
Map<String,IAttribute> aMap=[:];attrNms.each{aMap[it]=dim.getAttributeByName(it)}
Map<IAttribute,List[]> attrData=[:];aMap.values().each{a->if(a)attrData[a]=[[],[]]}
def wa={String attrName,IElement el,String val->IAttribute a=aMap[attrName];if(a){attrData[a][0]<<el;attrData[a][1]<<val}}
allNames.each{n->
    if(!ws.contains(n))return;IElement el=cache[n];if(!el)return
    wa("Previous",el,prevMap[n]?:"");wa("Next",el,nextMap[n]?:"");wa("Name",el,nameMap[n]?:n)
    if(monValMap[n]){wa("Month Value",el,monValMap[n]);wa("Month Short",el,monthShortMap[n]);wa("Month Long",el,monthLongMap[n])}
    if(currPeriodMap.containsKey(n))wa("Current Period",el,currPeriodMap[n])
    if(fiscalPeriodMap[n])wa("Fiscal Period",el,fiscalPeriodMap[n])
    if(priorYearMap[n])wa("Prior Year",el,priorYearMap[n])
    if(qtrValMap[n])wa("Quarter Value",el,qtrValMap[n])
    if(yrValMap[n])wa("Year Value",el,yrValMap[n])
    if(dimMap[n]){wa("Days In Month",el,dimMap[n]);wa("Weeks In Month",el,wimMap[n]);wa("Fortnights In Month",el,fimMap[n])}
    if(diyMap[n]){wa("Days In Year",el,diyMap[n]);wa("Weeks In Year",el,wiyMap[n]);wa("Fortnights In Year",el,fiyMap[n])}
    if(dayValMap[n])wa("Day Value",el,dayValMap[n])
    if(doWeeks&&weekNumMap[n])wa("Week",el,weekNumMap[n])
    if(dayAbbMap[n])wa("Day",el,dayAbbMap[n])
    if(doHolidays){wa("Public Holiday",el,phNational.getOrDefault(n,""));wa("Public Holiday State",el,phState.getOrDefault(n,""));wa("Observance",el,phObservance.getOrDefault(n,""))}
    if(doWorkDays&&dayTypeMap.containsKey(n)){wa("Day Type",el,dayTypeMap[n]);if(bizDayNumMap[n])wa("Business Day Number",el,bizDayNumMap[n])}
    if(doRetail&&dtRetail[n])wa("Retail Period",el,dtRetail[n])
    if(doRetail&&dtRetailWk[n])wa("Retail Week",el,dtRetailWk[n])
    if(retailOnly&&rwkStartDate[n])wa("Week Start Date",el,rwkStartDate[n])
    if(retailOnly&&rwkEndDate[n])wa("Week End Date",el,rwkEndDate[n])
    if(retailOnly&&rwkCurrentWeek.containsKey(n))wa("Current Week",el,rwkCurrentWeek[n])
}
allMonths.each{n->if(!ws.contains(n))return;IElement el=cache[n];if(el&&finYrMap[n])wa("Financial Year",el,finYrMap[n])}
if(doWorkDays)allMonths.each{n->if(!ws.contains(n))return;IElement el=cache[n];if(el)wa("Business Days In Month",el,bizDaysInMonthMap.getOrDefault(n,""))}
def toArr={List l->l.toArray(new IElement[0])}
LOG.info("  Writing attributes...")
attrData.each{attr,pair->if(pair[0])dim.addAttributeValues(attr,toArr(pair[0]),pair[1].toArray())}
LOG.info("  Done.")
// -----------------------------------------------------------------------------
// 8. DIMENSION PROPERTIES
// -----------------------------------------------------------------------------
try{
    LOG.info("  Setting dimension properties...")
    int currYear=Calendar.getInstance().get(Calendar.YEAR)
    List defCandidates=[pfx+currYear,currYear.toString(),pfx+endYear,endYear.toString()]
    if(retailOnly)defCandidates=[pfx+currYear+"-R",pfx+endYear+"-R"]
    String defaultEl=defCandidates.find{cache.containsKey(it)}?:(retailOnly&&allRY?allRY[-1]:(pfx+endYear))
    LOG.info("  Default element: "+defaultEl)
    IDimension sysDim=OLAP.getDatabase(olapConn).getDimensionByName("#_DIMENSION_")
    if(!sysDim){LOG.warn("  #_DIMENSION_ not found.")}
    else{
        IElement dimEl=sysDim.getElementByName(dimName,false)
        ICube propCube=dimEl?OLAP.getDatabase(olapConn).getCubeByName("#_#_DIMENSION_"):null
        if(!dimEl||!propCube){LOG.warn("  Property cube not found.")}
        else{
            IDimension[] cubeDims=propCube.getDimensions()
            IDimension attrDim=cubeDims.find{it.getName()!="#_DIMENSION_"&&!it.getName().contains("LANGUAGE")}
            IDimension langDim=cubeDims.find{it.getName().contains("LANGUAGE")}
            IElement langEl=langDim?.getElementByName("~",false)
            if(attrDim){
                ["Description":dimDesc,"DefaultParentElement":defaultEl,"DefaultReadElement":defaultEl,"TotalElement":defaultEl].each{k,v->
                    IElement attrEl=attrDim.getElementByName(k,false)
                    if(!attrEl){LOG.warn("  '"+k+"' not found.");return}
                    IElement[] path=new IElement[cubeDims.length]
                    cubeDims.eachWithIndex{d,i->path[i]=d.getName()=="#_DIMENSION_"?dimEl:d.getName().contains("LANGUAGE")?langEl:attrEl}
                    if(path.any{it==null}){LOG.warn("  Null path for '"+k+"'.");return}
                    def ctx=propCube.getCellLoadContext(ICube.SplashMode.SPLASH_DEFAULT,1,false,false)
                    propCube.loadCells([path] as IElement[][],[v] as Object[],ctx,null,false)
                    LOG.info("  Set "+k+" = "+v)
                }
            }
        }
    }
}catch(Exception ex){LOG.warn("  Properties error: "+ex.getMessage())}
// -----------------------------------------------------------------------------
// 9. DONE
// -----------------------------------------------------------------------------
LOG.info("=== Complete | "+allNames.size()+" elements | "+consos.size()+" pairs"+(retailOnly?" | retail-only":" | "+allMonths.size()+" months | "+allDates.size()+" dates")+" | "+allRWk.size()+" retail weeks | Rolling:"+rollingWindows)
