INSERT INTO COMMON.ACCOUNTABILITY_INT.CREATE_EMPLOYEES (
	NAME,
	CODE,
	OFFICENAME,
	DEPARTMENTNAME,
	TASKTYPENAME,
	TITLENAME,
	EMAIL,
	STARTDATE,
	APPROVALRIGHTS,
	USERACCESSGROUPID,
	DAILYHOURS,
	HOURLYCOSTRATE,
	WORKINGDAYS,
	CREATED_BY,
	CREATED_AT 
)

select 
	NAME,
	CODE,
	OFFICENAME,
	DEPARTMENTNAME,
	TASKTYPENAME,
	TITLENAME,
	EMAIL,
	STARTDATE,
	APPROVALRIGHTS,
	USERACCESSGROUPID,
	DAILYHOURS,
	HOURLYCOSTRATE,
	WORKINGDAYS,
	'JEDOX_INTEGRATOR_USR',
	'${vCurrentTimestamp}' 
from CONSUMPTION.ACCOUNTABILITY_SECURE.VW_CREATE_EMPLOYEE
where email = '${vHibobEmail}';
