SELECT DISTINCT PROJECT_ID, NAME
FROM CONSUMPTION.FLOAT.VW_CREATE_PROJECT_TASKS
WHERE NAME IS NOT NULL AND PROJECT_ID IS NOT NULL
--AND PROJECT_ID <> '11464244' --Time & Materials | No Client ID
AND PROJECT_ID <> '11518499' --Time & Materials
--AND PROJECT_ID <> '11468094'
