INSERT INTO COMMON.ACCOUNTABILITY_INT.UPDATE_EMPLOYEES (
	NAME,
	CODE,
	ORIGINAL_OFFICENAME,
	UPDATED_OFFICENAME,
	ORIGINAL_DEPARTMENTNAME,
	UPDATED_DEPARTMENTNAME,
	ORIGINAL_TASKTYPENAME,
	UPDATED_TASKTYPENAME,
	ORIGINAL_TITLENAME,
	UPDATED_TITLENAME,
	EMAIL,
	STARTDATE,
	APPROVALRIGHTS,
	USERACCESSGROUPID,
	DAILYHOURS,
	HOURLYCOSTRATE,
	WORKINGDAYS,
	CREATED_BY,
	CREATED_AT
)

select 
	NAME,
	CODE,
	ORIGINAL_OFFICENAME,
	OFFICENAME,
	ORIGINAL_DEPARTMENTNAME,
	DEPARTMENTNAME,
	ORIGINAL_TASKTYPENAME,
	DEFAULTTASKTYPENAME,
	ORIGINAL_TITLENAME,
	TITLENAME,
	EMAIL,
	STARTDATE,
	APPROVALRIGHTS,
	USERACCESSGROUPID,
	DAILYHOURS,
	HOURLYCOSTRATE,
	WORKINGDAYS,
	'JEDOX_INTEGRATOR_USR',
	'${vCurrentTimestamp}' 
from CONSUMPTION.ACCOUNTABILITY_SECURE.VW_UPDATE_EMPLOYEE
where email = '${vHibobEmail}';
