SELECT 
REPLICATION_DATETIME, 
ACTIVE,
NAMESPACE, 
DOMAIN_NAME,
FRIENDLY_NAME,
HAS_SFTP,
LOG_URI,
LOGIN_LINK,
MAX_BACKUP_TIME,
PUBLIC_IP,
REGION,
TYPE,
SUPPORT_ON
FROM JEDOX.PUBLIC.MACHINES
WHERE REPLICATION_DATETIME > '${vFrom}' AND REPLICATION_DATETIME < '${vTo}'
--GROUP BY NAMESPACE, ACTIVE, DOMAIN_NAME, FRIENDLY_NAME, HAS_SFTP, LOG_URI, LOGIN_LINK, MAX_BACKUP_TIME, PUBLIC_IP, REGION, TYPE, SUPPORT_ON
