INSERT INTO COMMON.FLOAT_INT.CREATED_PROJECTS
(
  	NAME,
	PROJECT_CODE,
	CLIENT_ID,
	BUDGET_TYPE,
	BUDGET_PRIORITY,
	START_DATE,
	PROJECT_MANAGER,
	ALL_PMS_SCHEDULE,
	STATUS,
	ACTIVE,
	NON_BILLABLE,
  	TAGS
)
SELECT * 
FROM CONSUMPTION.FLOAT.VW_CREATE_PROJECTS
WHERE PROJECT_CODE = '${vProjectCode}';
