INSERT INTO COMMON.FLOAT_INT.CREATED_PROJECT_TASKS
(
	JOB_NUMBER,
	NAME,
	PROJECT_ID,
	BUDGET
)
SELECT * FROM CONSUMPTION.FLOAT.VW_CREATE_PROJECT_TASKS
WHERE PROJECT_ID = '${vProjectID}' AND NAME = '${vName}';
