INSERT INTO COMMON.FLOAT_INT.UPDATED_PROJECT_TASKS
(
	JOB_NUMBER,
	NAME,
	PROJECT_ID,
  	TASK_META_ID,
    UPDATED_BUDGET,
    ORIGINAL_BUDGET
)
SELECT * FROM CONSUMPTION.FLOAT.VW_UPDATE_PROJECT_TASKS
WHERE TASK_META_ID = '${vTaskID}';
