INSERT INTO COMMON.FLOAT_INT.UPDATED_PROJECTS
(
	PROJECT_ID,
	PROJECT_CODE,
	CLIENT_ID,
	UPDATED_BUDGET_TYPE,
	ORIGINAL_BUDGET_TYPE,
	UPDATED_BUDGET_PRIORITY,
	ORIGINAL_BUDGET_PRIORITY,
	UPDATED_STATUS,
	ORIGINAL_STATUS,
	UPDATED_NON_BILLABLE,
	ORIGINAL_NON_BILLABLE,
  	ORIGINAL_TAGS,
  	UPDATED_TAGS
)
SELECT * FROM CONSUMPTION.FLOAT.VW_UPDATE_PROJECTS
WHERE PROJECT_CODE = '${vProjectCode}';
