INSERT INTO JEDOX.PUBLIC.${vTableSnowflake}(
	ACTIVE,
	COMPANY_IDX,
	DESIGNV2,
	DOMAIN_NAME,
	FRIENDLY_NAME,
	HAS_SFTP,
	ID,
	ID_SUB_REGION,
	LOG_URI,
	LOGIN_LINK,
	MAX_BACKUP_TIME,
	NAMESPACE,
	PUBLIC_IP,
	REGION,
	SECRET,
	STATE,
	SUPPORT_ON,
	TYPE
)
SELECT TO_BOOLEAN($1),$2,TO_BOOLEAN($3),$4,$5,TO_BOOLEAN($6),$7,$8,$9,$10,TO_DOUBLE($11),$12,$13,$14,$15,TO_DOUBLE($16),TO_BOOLEAN($17),$18
FROM @JEDOX.PUBLIC.JEDOX_STAGE/${vTableSnowflake}.csv.gz (FILE_FORMAT => 'JEDOX_LOG_FORMAT');
