INSERT INTO JEDOX.LOGS.${vTableSnowflake}(
	MACHINE,
	TIME_UTC,
	LEVEL,
	SERVICE,
	LOG
)
SELECT $1,$2,$3,$4,$5
FROM @JEDOX.PUBLIC.JEDOX_STAGE/${vTableSnowflake}.csv.gz (FILE_FORMAT => 'JEDOX_LOG_FORMAT');
