SELECT 
    CHILD_ELEMENT,
    NAME,
    ID_NAME,
    CONVERSION_TYPE
FROM CONSUMPTION.JEDOX_DIMENSIONS.VW_BS_ACCOUNT
WHERE TRY_TO_NUMBER(CHILD_ELEMENT) IS NOT NULL

UNION ALL

SELECT 
    'Current Year Earnings' AS CHILD_ELEMENT,
    NULL AS NAME,
    NULL AS ID_NAME,
    NULL AS CONVERSION_TYPE

ORDER BY CHILD_ELEMENT;
